In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("Salaries.csv")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

## ***1. Display Top 10  Rows of The Dataset***

In [4]:
df.head(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
5,6,DAVID SULLIVAN,ASSISTANT DEPUTY CHIEF II,118602.0,8601.0,189082.74,NaN,316285.74,316285.74,2011,NaN,San Francisco,NaN
6,7,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011,NaN,San Francisco,NaN
7,8,DAVID KUSHNER,DEPUTY DIRECTOR OF INVESTMENTS,256576.96,0.0,51322.5,NaN,307899.46,307899.46,2011,NaN,San Francisco,NaN
8,9,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011,NaN,San Francisco,NaN
9,10,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011,NaN,San Francisco,NaN

## ***2.Check Last 10 Rows of The Dataset***

In [6]:
df.tail(10)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148644,148645,Randy D Winn,"Stationary Eng, Sewage Plant",0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148646,148647,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,NaN,San Francisco,PT
148650,148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,NaN,San Francisco,PT

## ***3. Find Shape our Dataset (Number of Rows and Number of Columns)***

In [8]:
df.shape

(148654, 13)

In [9]:
df.shape[0]

148654

## ***4. Getting ALl Information About Our Dataset***

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

## ***5. Check Null Values In the Dataset***

In [13]:
df.isnull()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,False,False,False,False,False,False,True,False,False,False,True,False,True
1,False,False,False,False,False,False,True,False,False,False,True,False,True
2,False,False,False,False,False,False,True,False,False,False,True,False,True
3,False,False,False,False,False,False,True,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,False,False,False,False,False,False,False,False,False,False,True,False,False
148650,False,False,False,False,False,False,False,False,False,False,True,False,True
148651,False,False,False,False,False,False,False,False,False,False,True,False,True
148652,False,False,False,False,False,False,False,False,False,False,True,False,True
148653,False,False,False,False,False,False,False,False,False,False,True,False,False

In [14]:
df.isnull().sum()

Id                       0
EmployeeName             0
JobTitle                 0
BasePay                605
OvertimePay              0
OtherPay                 0
Benefits             36159
TotalPay                 0
TotalPayBenefits         0
Year                     0
Notes               148654
Agency                   0
Status              110535
dtype: int64

## ***6. Drop ID, Notes, Agency and Status Columns***

In [16]:
df.drop(['Id','Notes','Agency','Status'])

KeyError: "['Id', 'Notes', 'Agency', 'Status'] not found in axis"

In [18]:
df = df.drop(['Id','Notes','Agency','Status'],axis=1)

In [20]:
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,Not provided,Not provided,Not Provided,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

## ***7. Get Overall Statistics About the Dataframe***

In [23]:
df.describe()

            TotalPay  TotalPayBenefits           Year
count  148654.000000     148654.000000  148654.000000
mean    74768.321972      93692.554811    2012.522643
std     50517.005274      62793.533483       1.117538
min      -618.130000       -618.130000    2011.000000
25%     36168.995000      44065.650000    2012.000000
50%     71426.610000      92404.090000    2013.000000
75%    105839.135000     132876.450000    2014.000000
max    567595.430000     567595.430000    2014.000000

In [25]:
df.describe(include='all')

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
count,148654,148654,148049.0,148654.0,148654.0,112495.0,148654.000000,148654.000000,148654.000000
unique,110811,2159,109900.0,66555.0,84968.0,99635.0,NaN,NaN,NaN
top,Kevin Lee,Transit Operator,0.0,0.0,0.0,0.0,NaN,NaN,NaN
freq,13,7036,875.0,66103.0,35218.0,1053.0,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,74768.321972,93692.554811,2012.522643
std,NaN,NaN,NaN,NaN,NaN,NaN,50517.005274,62793.533483,1.117538
min,NaN,NaN,NaN,NaN,NaN,NaN,-618.130000,-618.130000,2011.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,36168.995000,44065.650000,2012.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,71426.610000,92404.090000,2013.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,105839.135000,132876.450000,2014.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,567595.430000,567595.430000,2014.000000

## ***8. Find Occurrence of The Employee Names (Top 5)***

In [28]:
df.EmployeeName.value_counts().head()

EmployeeName
Kevin Lee       13
Richard Lee     11
Steven Lee      11
William Wong    11
Stanley Lee      9
Name: count, dtype: int64

## ***9. Find The Number of Unique Job Titles***

In [32]:
df.JobTitle

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: object

In [34]:
# pd.options.display.max_rows = None

In [36]:
df.JobTitle

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: object

In [38]:
df.JobTitle.unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

In [40]:
df.JobTitle

0         GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
1                        CAPTAIN III (POLICE DEPARTMENT)
2                        CAPTAIN III (POLICE DEPARTMENT)
3                   WIRE ROPE CABLE MAINTENANCE MECHANIC
4           DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
                               ...
148649                                         Custodian
148650                                      Not provided
148651                                      Not provided
148652                                      Not provided
148653                        Counselor, Log Cabin Ranch
Name: JobTitle, Length: 148654, dtype: object

In [42]:
for i in df.JobTitle.unique():
    print(i)

GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY
CAPTAIN III (POLICE DEPARTMENT)
WIRE ROPE CABLE MAINTENANCE MECHANIC
DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)
ASSISTANT DEPUTY CHIEF II
BATTALION CHIEF, (FIRE DEPARTMENT)
DEPUTY DIRECTOR OF INVESTMENTS
CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)
EXECUTIVE CONTRACT EMPLOYEE
DEPARTMENT HEAD V
COMMANDER III, (POLICE DEPARTMENT)
CAPTAIN, EMERGENCYCY MEDICAL SERVICES
ASSISTANT MEDICAL EXAMINER
CAPTAIN, FIRE SUPPRESSION
CHIEF OF POLICE
DEPUTY CHIEF III (POLICE DEPARTMENT)
INSPECTOR III, (POLICE DEPARTMENT)
ELECTRONIC MAINTENANCE TECHNICIAN
ADMINISTRATOR, SFGH MEDICAL CENTER
LIEUTENANT III (POLICE DEPARTMENT)
FIREFIGHTER
NURSING SUPERVISOR PSYCHIATRIC
MAYOR
LIEUTENANT, FIRE DEPARTMENT
INCIDENT SUPPORT SPECIALIST
ANESTHETIST
DISTRICT ATTORNEY
ELECTRICAL TRANSIT MECHANIC, ASSISTANT SUPERVISOR
PORT DIRECTOR
LIEUTENANT, BUREAU OF FIRE PREVENTION AND PUBLIC S
SENIOR PHYSICIAN SPECIALIST
FIRE FIGHTER PARAMEDIC
MANAGER VII
TRANSIT SUPERVISOR
INSPECTOR, BUREAU OF FIRE PREVENTION AND PUBLIC SA
MANAGER VIII
DEPUTY DIRECTOR II - MUNICIPAL TRANSPORTATION AG
NURSING SUPERVISOR
POLICE OFFICER III
SHERIFF'S LIEUTENANT
DEPUTY DIRECTOR V
SUPERVISING PHYSICIAN SPECIALIST
DEPARTMENT HEAD IV
FORENSIC TOXICOLOGIST
CONFIDENTIAL CHIEF ATTORNEY II (CIVIL & CRIMINAL)
SERGEANT III (POLICE DEPARTMENT)
DEPUTY SHERIFF
NURSE MANAGER
ELECTRICAL TRANSIT SYSTEM MECHANIC
CITY ATTORNEY
MARINE ENGINEER OF FIRE BOATS
CHIEF ATTORNEY I (CIVIL & CRIMINAL)
CAPTAIN, BUREAU OF FIRE PREVENTION AND PUBLIC SAFE
ELECTRICAL TRANSIT SHOP SUPERVISOR I
POLICE OFFICER I
POLICE OFFICER II
SERGEANT I (POLICE DEPARTMENT)
SPECIAL ASSISTANT XXII
DEPUTY DIRECTOR IV
WIRE ROPE CABLE MAINTENANCE SUPERVISOR
PUBLIC DEFENDER
SHERIFF
HUMAN RESOURCES DIRECTOR
INVESTIGATOR, BUREAU OF FIRE INVESTIGATION
ASSISTANT CHIEF ATTORNEY II
DEPUTY DIRECTOR III
PHARMACIST
TRANSIT OPERATIONS SPECIALIST
DEPARTMENT HEAD III
CHIEF PROBATION OFFICER, JUVENILE COURT
SHERIFF'S SERGEANT
ASSISTANT INSPECTOR (POLICE DEPARTMENT)
DIAGNOSTIC IMAGING TECH II
DIAGNOSTIC IMAGING TECH III
CHIEF ADULT PROBATION OFFICER
MANAGER VI
FIRE SAFETY INSPECTOR II
MAINTENANCE MACHINIST
ASSISTANT INSPECTOR III (POLICE DEPARTMENT)
DEPUTY DIRECTOR I - MUNICIPAL TRANSPORTATION AGE
DIRECTOR, EMPLOYEE RELATIONS DIVISION
ASSISTANT CHIEF ATTORNEY I
TRAIN CONTROLLER
PHYSICIAN ASSISTANT
PHYSICIAN SPECIALIST
AUTOMOTIVE MECHANIC SUPERVISOR I
ATTORNEY (CIVIL/CRIMINAL)
SERGEANT II (POLICE DEPARTMENT)
ELECTRICIAN
NURSE PRACTITIONER
MECHANICAL SHOP AND EQUIPMENT SUPERINTENDENT
HEAD ATTORNEY, CIVIL AND CRIMINAL
PRINCIPAL CIVIL ENGINEER
ASSOCIATE ENGINEER
PROJECT MANAGER IV
PILOT OF FIRE BOATS
DEPARTMENT HEAD I
SENIOR ENGINEER
COURT EXECUTIVE OFFICER
ENGINEER
ASSISTANT SHERIFF
BUILDINGS AND GROUNDS MAINTENANCE SUPERINTENDENT
ELECTRONIC MAINTENANCE TECHNICIAN ASSISTANT SUPERV
CLINICAL PHARMACIST
DEPARTMENT HEAD II
CLINICAL NURSE SPECIALIST
NURSE MIDWIFE
ELECTRICAL TRANSIT MECHANIC SUPERVISOR I
MANAGER V
ATTORNEY FOR THE PUBLIC ADMINISTRATOR
CHIEF DEPUTY SHERIFF
SENIOR DEPUTY SHERIFF
PROJECT MANAGER III
TRACK MAINTENANCE WORKER SUPERVISOR I
MAYORAL STAFF XVII
MANAGER VII - MUNICIPAL TRANSPORTATION AGENCY
HEATING AND VENTILATING INSPECTOR
ASST. CHIEF PROBATION OFFICER-JUVENILE PROBATION
DIRECTOR, INFORMATION TECHNOLOGY GROUP
UTILITY PLUMBER SUPERVISOR II
COMMUNICATIONS LINE WORKER SUPERVISOR II
ASSISTANT INSPECTOR II (POLICE DEPARTMENT)
ASSESSOR
MANAGER VIII - MUNICIPAL TRANSPORTATION AGENCY
MANAGER IV
INSPECTOR, (POLICE DEPARTMENT)
IS ENGINEER - PRINCIPAL
REGISTERED NURSE
SPECIAL NURSE
INFORMATION SERVICES MANAGER
TRANSMISSION LINE SUPERVISOR I
SUPERVISING PHARMACIST
SEWAGE TREATMENT PLANT SUPERINTENDENT
TREASURER
SENIOR POWER GENERATION TECHNICIAN
DEPUTY DIRECTOR II
CHIEF DISTRICT ATTORNEY'S INVESTIGATOR
LANDSCAPE ARCHITECTURAL ASSOCIATE II
ARCHITECTURAL ASSOCIATE  I
LANDSCAPE ARCHITECT
ARCHITECT
STATIONARY ENGINEER
PLUMBING INSPECTOR
AUTOMOTIVE MECHANIC
CHIEF STATIONARY ENGINEER
SENIOR COURT STAFF ATTORNEY
HEAD PARK PATROL OFFICER
UNDERSHERIFF
ASSISTANT ELECTRONIC MAINTENANCE TECHNICIAN
SHERIFF'S CAPTAIN
MANAGER III
BOARD SECRETARY - MUNICIPAL TRANSPORTATION AGENC
WATER CONSTRUCTION AND MAINTENANCE SUPERINTENDENT
LIEUTENANT I, (POLICE DEPARTMENT)
LIEUTENANT II (POLICE DEPARTMENT)
DIAGNOSTIC IMAGING TECH I
MANAGER II - MUNICIPAL TRANSPORTATION AGENCY
MANAGER VI - MUNICIPAL TRANSPORTATION AGENCY
ATTORNEY, TAX COLLECTOR
COURT COMMISSIONER
PRINCIPAL ADMINISTRATIVE ANALYST
SENIOR RADIO TECHNICIAN
ADMINISTRATIVE ENGINEER
BUILDING INSPECTOR
CHIEF WATER SERVICE INSPECTOR
POWER GENERATION SUPERVISOR
TRANSIT OPERATOR
UTILITY PLUMBER SUPERVISOR I
RADIOLOGIC TECHNOLOGIST SUPERVISOR
DENTIST
BUILDING PLANS ENGINEER
INSPECTOR II, (POLICE DEPARTMENT)
TELECOMMUNICATIONS TECHNICIAN SUPERVISOR
SUPERVISING ELECTRONIC MAINTENANCE TECHNICIAN
INSTITUTIONAL POLICE SERGEANT
TRANSIT POWER LINE SUPERVISOR I
SENIOR COUNSELOR, JUVENILE HALL
COURT ADMINISTRATOR
PLUMBER SUPERVISOR I
COURT COMPUTER SYSTEMS MANAGER
SENIOR CONSTRUCTION INSPECTOR
CRIMINALIST III
TRANSIT POWER LINE WORKER
SEWER REPAIR SUPERVISOR
SENIOR LIGHT RAIL VEHICLE EQUIPMENT ENGINEER
TRANSMISSION AND DISTRIBUTION LINE WORKER
MANAGER II
ARCHITECTURAL ASSOCIATE II
AUTOMOTIVE TRANSIT SHOP SUPERVISOR I
MANAGER V - MUNICIPAL TRANSPORTATION AGENCY
IS PROJECT DIRECTOR
TRANSIT CAR CLEANER
CHIEF STATIONARY ENGINEER, WATER TREATMENT PLANT
PLUMBER
DISABILITY ACCESS COORDINATOR
AUTOMOTIVE MECHANIC ASSISTANT SUPERVISOR
AUTOMOTIVE MACHINIST ASSISTANT SUPERVISOR
LAW LIBRARIAN
PROJECT MANAGER II
SENIOR STATIONARY ENGINEER
TRANSIT POWER LINE WORKER SUPERVISOR II
ASST. CHIEF, BUREAU OF CLAIMS INVEST. & ADMIN
IS BUSINESS ANALYST - PRINCIPAL
POWER GENERATION TECHNICIAN II
CABLE SPLICER
CONSTRUCTION INSPECTOR
IS ENGINEER - SENIOR
PLANNER V
CRIME LABORATORY MANAGER
SHEET METAL WORKER SUPERVISOR II
COMMUNICATIONS SYSTEMS TECHNICIAN
IS ENGINEER - JOURNEY
SUPERINTENDENT OF WATER TREATMENT FACILITIES
STATION AGENT, MUNICIPAL RAILWAY
STRUCTURAL ENGINEER
PUBLIC HEALTH NURSE
COURT STAFF ATTORNEY II
HEAD AIRPORT ELECTRICIAN
ASSISTANT DIRECTOR OF CLINICAL SERVICES II
FIRE PROTECTION ENGINEER
SPECIAL ASSISTANT XVI
ASSISTANT DEPUTY DIRECTOR, PORT
FIRE RESCUE PARAMEDIC
DIRECTOR, FISCAL SERVICES
DISTRICT ATTORNEY'S INVESTIGATOR
TRANSIT PAINT SHOP SUPERVISOR I
ELECTRICIAN SUPERVISOR II
PRINCIPAL DISTRICT ATTORNEY'S INVESTIGATOR
BUILDINGS AND GROUNDS MAINTENANCE SUPERVISOR
SENIOR WATER SERVICE INSPECTOR
IS BUSINESS ANALYST - SENIOR
MAINTENANCE CONTROLLER
ELECTRICIAN SUPERVISOR I
MANAGER, EMPLOYEE RELATIONS DIV
TRAFFIC HEARING OFFICER
ASSISTANT ENGINEER
LANDSCAPE ARCHITECTURAL ASSOCIATE I
CHIEF BUILDING INSPECTOR
MAINTENANCE MACHINIST SUPERVISOR I
MANAGER IV - MUNICIPAL TRANSPORTATION AGENCY
UTILITY PLUMBER
SENIOR ELECTRICAL INSPECTOR
ELECTRICAL INSPECTOR
SENIOR STATIONARY ENGINEER, WATER TREATMENT PLANT
COMMUNICATION LINE SUPERVISOR I
ELECTRICAL LINE WORKER
MAYORAL STAFF XVI
AIRPORT MECHANICAL MAINTENANCE SUPERVISOR
COURT REPORTER COORDINATOR
CHIEF PLUMBING INSPECTOR
OPERATING ROOM NURSE
WELDER
MENTAL HEALTH TREATMENT SPECIALIST
TRANSPORTATION SAFETY SPECIALIST
SENIOR POLICE COMMUNICATIONS DISPATCHER
UTILITY SPECIALIST
CEMENT FINISHER SUPERVISOR II
ASSISTANT COURT REPORTER COORDINATOR
PRINCIPAL REAL PROPERTY OFFICER
RESEARCH PSYCHOLOGIST
LOCKSMITH SUPERVISOR I
SUPERVISING CHEMIST
SENIOR PLUMBING INSPECTOR
OPERATING ENGINEER, UNIVERSAL
LABORATORY SERVICES MANAGER
MANAGER I
MANAGER, UNIFIED FAMILY COURT SERVICES
DIRECTOR, HUMAN RESOURCES
SENIOR BUILDING INSPECTOR
TRANSIT MANAGER II
PLANNER IV
EMERGENCY MEDICAL SERVICES AGENCY SPECIALIST
PUBLIC SAFETY COMMUNICATIONS DISPATCHER
WATER OPERATIONS ANALYST
CHIEF ELECTRICAL INSPECTOR
TRAFFIC SIGNAL ELECTRICIAN
AUTOMOTIVE BODY AND FENDER WORKER
APPRENTICE STATIONARY ENGINEER
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I
AUTOMOTIVE MACHINIST
SUPERVISING PURCHASER
CHIEF STATIONARY ENGINEER, SEWAGE PLANT
COURT COMPUTER FACILITIES COORDINATOR
PLUMBER SUPERVISOR II
MANAGER III - MUNICIPAL TRANSPORTATION AGENCY
CLAIMS INVESTIGATOR
STEAMFITTER
PROTECTIVE SERVICES SUPERVISOR
CARPENTER SUPERVISOR I
MAYORAL STAFF XV
COUNSELOR, LOG CABIN RANCH
CHIEF HOUSING INSPECTOR
MEDICAL EXAMINER'S INVESTIGATOR II
DIRECTOR, JUVENILE HALL
IS PROGRAMMER ANALYST - PRINCIPAL
TRAF SIGNAL ELECTRICIAN SUP II
IS ADMINISTRATOR III
ASSISTANT CHIEF DISTRICT ATTORNEY'S INVESTIGATOR
STEAMFITTER ASSISTANT SUPERVISOR
SENIOR STATIONARY ENGINEER, SEWAGE PLANT
COURT REPORTER
AIRPORT ELECTRICIAN
AIRPORT ELECTRICIAN SUPERVISOR
COURT MANAGER
HEALTH PROGRAM COORDINATOR III
SUPERVISING WASTEWATER CONTROL INSPECTOR
TRAF SIGNAL ELECTRICIAN SUP I
LINE INSPECTOR
PRINCIPAL ADMINISTRATIVE ANAYLST II
WATER SERVICE INSPECTOR
PUBLIC RELATIONS MANAGER
SENIOR ENVIRONMENTAL HEALTH INSPECTOR
CONTRACT COMPLIANCE OFFICER II
SENIOR INDUSTRIAL HYGIENIST DEPT OF PUBLIC HEALTH
SAFETY OFFICER
AUTOMOTIVE MACHINIST SUPERVISOR I
PLANNER IV-ENVIRONMENTAL REVIEW
DIVISION DIRECTOR ADULT PROBATION
PROTECTIVE SERVICES WORKER
MEDICAL EXAMINER'S INVESTIGATOR III
AUTOMOTIVE SERVICE WORKER
DIRECTOR, PROBATE
IS ADMINISTRATOR - SUPERVISOR
SENIOR HOUSING INSPECTOR
SEWER SERVICE WORKER
STREET REPAIR SUPERVISOR II
ELECTRIC MOTOR REPAIRER
COMMUNICATIONS DIRECTOR
COURT COMPUTER APPLICATIONS PROGRAMMER
DIAGNOSTIC IMAGING TECH IV
PROJECT MANAGER I
ASPHALT FINISHER SUPERVISOR I
TRANSIT MANAGER I
CRIMINALIST II
CHIEF MICROBIOLOGIST
CHIEF SURVEYOR
SENIOR ADMINISTRATIVE ANALYST
PSYCHIATRIC TECHNICIAN
SUPERVISING BIOLOGIST
AIRPORT OPERATIONS SUPERVISOR
TRANSIT PLANNER IV
MEDIA/SECURITY SYSTEMS SUPERVISOR
SENIOR DISTRICT ATTORNEY'S INVESTIGATOR
PRINCIPAL PERSONNEL ANALYST
SENIOR PHYSICAL THERAPIST
SENIOR OCCUPATIONAL THERAPIST
SHELTER VETERINARIAN
CHIEF FIRE ALARM DISPATCHER
DEPUTY DIRECTOR I
EXECUTIVE ASSISTANT TO THE GENERAL MANAGER, RETIRE
AIRPORT ECONOMIC PLANNER
SWITCH REPAIRER
POWER HOUSE ELECTRICIAN SUPERVISOR I
SAFETY ANALYST
BIOLOGIST III
PARKING ENFORCEMENT ADMINISTRATOR
PRINCIPAL ENVIRONMENTAL HEALTH INSPECTOR
SENIOR EMPLOYEE RELATIONS REPRESENTATIVE
PAINTER SUPERVISOR I
SENIOR SYSTEMS ACCOUNTANT
COUNSELOR, FAMILY COURT SERVICE
GOVERNMENT AND PUBLIC AFFAIRS MANAGER
ELECTRONIC INSTRUMENTATION TECHNICIAN,WTR PLTNCN
CAR AND AUTO PAINTER
PERFORMANCE ANALYST III - PROJECT MANAGER
UTILITY PLUMBER APPRENTICE
PRINCIPAL MANAGEMENT ANALYST
LOCKSMITH
SENIOR AIRPORT COMMUNICATIONS DISPATCHER
SENIOR PROPERTY MANAGER, PORT
HEAVY EQUIPMENT OPERATIONS SUPERVISOR
MAINTENANCE PLANNER
SENIOR STREET INSPECTOR
SENIOR REAL PROPERTY OFFICER
ASSISTANT DIRECTOR OF CLINICAL SERVICES I
TRUCK DRIVER
DIRECTOR, PROBATION SERVICES
SENIOR CLAIMS INVESTIGATOR
TRACK MAINTENANCE WORKER
WATER AND POWER MAINTENANCE SUPERVISOR I
ASSOCIATE AFFIRMATIVE ACTION COORDINATOR
POLICE COMMUNICATIONS SHIFT SUPERVISOR
STREET ENVIRONMENTAL SERVICES OPERATIONS SUPERVI
ASSISTANT LAW LIBRARIAN
CEMENT FINISHER SUPERVISOR I
SENIOR PLAN CHECKER
STATIONARY ENGINEER, WATER TREATMENT PLANT
MAINTENANCE MANAGER
CLERK
CRANE MECHANIC SUPERVISOR
AIRPORT COMMUNICATIONS OPERATOR
MANAGER I - MUNICIPAL TRANSPORTATION AGENCY
SUPERVISING CLINICAL PSYCHOLOGIST
CHEMIST III
ARCHITECTURAL ADMINISTRATOR
PRINCIPAL REAL PROPERTY APPRAISER
GENERAL LABORER SUPERVISOR I
SUPERVISING PARTS STOREKEEPER
CITY SHOPS ASSISTANT SUPERINTENDENT
INDUSTRIAL HYGIENIST
HOUSING INSPECTOR
MATERIALS COORDINATOR
PRINCIPAL PERSONAL PROPERTY AUDITOR
STATIONARY ENGINEER, SEWAGE PLANT
LICENSED VOCATIONAL NURSE
MARITIME MARKETING REPRESENTATIVE
COURT COMPUTER SYSTEMS ENGINEER II
COURT COMPUTER APPLICATIONS ANALYST
SENIOR HUMAN RESOURCES ANALYST
PRINCIPAL ENVIRONMENTAL SPECIALIST
SUPERVISING ADULT PROBATION OFFICER
SUPERVISING PROBATION OFFICER, JUVENILE COURT
SUPERVISING AUDITOR
CLAIMS ADJUSTER
ELEVATOR AND CRANE TECHNICIAN
COURT SUPERVISOR II
MEMBER, BOARD OF SUPERVISORS
PARTS STOREKEEPER
WATER CONSERVATION ADMINISTRATOR
TRANSIT CAR CLEANER ASSISTANT SUPERVISOR
SHEET METAL SUPERVISOR I
MAYORAL STAFF XIII
SENIOR CLAIMS INVESTIGATOR,CITY ATTORNEY'S OFFICE
SENIOR MAINTENANCE CONTROLLER
GLAZIER
FISCAL SERVICES COORDINATOR
SECRETARY TO THE PRESIDING JUDGE
HEALTH WORKER IV
POWER PLANT SUPERVISOR I
OCCUPATIONAL THERAPIST
SURVEY ASSOCIATE
AUTOMOTIVE SERVICE WORKER ASSISTANT SUPERVISOR
SENIOR COMMUNITY DEVELOPMENT SPECIALIST I
CHIEF VICTIM/WITNESS INVESTIGATOR
MEDIA/SECURITY SYSTEMS SPECIALIST
MAYORAL STAFF XIV
GENERAL LABORER
DEPUTY PROBATION OFFICER
CARPENTER
PARK PATROL OFFICER
EXECUTIVE DIRECTOR, SOUTHEAST COMMUNITY FACILITY
PHYSICAL THERAPIST
SENIOR POWER HOUSE OPERATOR
PARKING CONTROL OFFICER
SENIOR PERSONNEL ANALYST
INSTITUTIONAL POLICE OFFICER
PHARMACY TECHNICIAN
AUDIOLOGIST
ELIGIBILITY WORKER
ASSISTANT SUPERINTENDENT RECREATION
SHEET METAL WORKER
ASPHALT PLANT SUPERVISOR I
SENIOR ACCOUNT CLERK
COURT INVESTIGATOR
STAGE ELECTRICIAN
SECURITY ANALYST
PRINCIPAL PAYROLL AND PERSONNEL CLERK
SENIOR COMMUNITY DEVELOPMENT SPECIALIST II
TRAFFIC SIGN MANAGER
ELECTRIC MOTOR REPAIR SUPERVISOR I
TRANSIT PLANNER III
REGULATORY SPECIALIST
PROBATE EXAMINER
HOSPITAL ELIGIBILITY WORKER SUPERVISOR
COURT ASSISTANT - SENIOR, SUPERIOR COURT
MUNICIPAL STADIUM GROUNDSKEEPER
BRICKLAYER
PLANNER III-ENVIRONMENTAL REVIEW
ASSISTANT FORENSIC TOXICOLOGIST I
FARE INSPECTIONS SUPERVISOR/INVESTIGATOR
EMPLOYMENT AND TRAINING SPECIALIST VI
PIPE WELDER
PARK SECTION SUPERVISOR
ENVIRONMENTAL HEALTH INSPECTOR
PRINCIPAL FARE COLLECTIONS RECEIVER
AIRPORT SAFETY OFFICER
MARRIAGE, FAMILY & CHILD COUNSELOR (MFCC)
COORDINATOR OF CITIZEN INVOLVEMENT
TREE TOPPER SUPERVISOR I
COURT INTERPRETER SUPERVISOR
SURGICAL PROCEDURES TECHNICIAN
PLANNER III
MENTAL HEALTH REHABILITATION WORKER
PATIENT ACCOUNTS SUPERVISOR
STREET INSPECTION SUPERVISOR
COMMUNICATIONS DISPATCHER II
POWER HOUSE OPERATOR
SENIOR MICROBIOLOGIST
IS ENGINEER - ASSISTANT
ELECTRICAL LINE HELPER
ASSISTANT MATERIALS COORDINATOR
WORKER'S COMPENSATION SUPERVISOR I
ASSISTANT TO THE DIRECTOR, PUBLIC AFFAIRS       RS
CLAIMS INVESTIGATOR CITY ATTORNEYS OFFICE
IS TRAINER - SENIOR
SPEECH PATHOLOGIST
NURSING ASSISTANT
COURT TRAINING SPECIALIST
ENGINEERING ASSOCIATE II
CLINICAL PSYCHOLOGIST
IS BUSINESS ANALYST
GARDENER
AIRPORT PROPERTY SPECIALIST I
BOARD/COMMISSION SECRETARY III
BENEFITS SUPERVISOR
LEGISLATIVE ASSISTANT
CEMENT MASON
LIBRARIAN III
REAL PROPERTY OFFICER
ASSISTANT RENTAL MANAGER, PORT
ORNAMENTAL IRON WORKER SUPERVISOR I
FUSION WELDER
SUPERVISING WELFARE FRAUD INVESTIGATOR
TRAINING COORDINATOR
PAINTER
SENIOR PARKING CONTROL OFFICER
SENIOR PURCHASER
PROGRAM SUPPORT ANALYST
FOOD SERVICE MANAGER ADMINISTRATOR
CONTRACT COMPLIANCE OFFICER I
MEDICAL SOCIAL WORK SUPERVISOR
WATERSHED FORESTER MANAGER
HEAVY EQUIPMENT OPERATIONS ASSISTANT SUPERVISOR
ADMINISTRATIVE ANALYST III
MOBILE EQUIPMENT SUPERVISOR
GENERAL UTILITY MECHANIC
ASSOCIATE AUDITOR
COURT SUPERVISOR I
APPRENTICE STATIONARY ENGINEER, SEWAGE PLANT
TRACK MAINTENANCE SUPERINTENDENT,MUNICIPAL RAILWAY
PATTERN MAKER
EXECUTIVE ASSISTANT TO THE ADMINISTRATOR, S.F.G.H.
IS PROGRAMMER ANALYST - SENIOR
ASSISTANT CLERK, BOARD OF SUPERVISORS
SENIOR REAL PROPERTY APPRAISER
EPIDEMIOLOGIST II
ADMINISTRATIVE SERVICES MANAGER
PILEDRIVER SUPERVISOR I
PERSONNEL PAYROLL REPRESENTATIVE
STREET INSPECTOR
WASTEWATER CONTROL INSPECTOR
SENIOR PERSONAL PROPERTY AUDITOR
BIOLOGIST I/II
SENIOR PSYCHIATRIC SOCIAL WORKER
SENIOR HEALTH PROGRAM PLANNER
SENIOR ENVIRONMENT SPECIALIST
SENIOR INVESTIGATOR, OFFICE OF CITIZEN'S COMPLAINT
HEALTH CARE ANALYST
SENIOR PAYROLL AND PERSONNEL CLERK
SECRETARY I
SOFT FLOOR COVERER SUPERVISOR
APPRENTICE STATIONARY ENGINEER,WATER TREATMENT PLN
SECRETARY, COMMISSION ON THE ENVIRONMENT
PSYCHIATRIC SOCIAL WORKER
MAINTENANCE MACHINIST ASSISTANT SUPERVISOR
SENIOR SOCIAL WORKER
COORDINATOR, HUMAN RIGHTS COMMISSION
SENIOR HEALTH EDUCATOR
CURATOR IV
COUNSELOR II
MUSEUM SECURITY SUPERVISOR
SUPERVISOR, TRAFFIC AND STREET SIGNS
SENIOR CLERK
PRINCIPAL ACCOUNTANT
FEASIBILITY ANALYST, PORT
AIRPORT POLICE SERVICES AIDE
MAYOR'S PROGRAM MANAGER
PILEDRIVER ENGINE OPERATOR
SENIOR PUBLIC DEFENDER'S INVESTIGATOR
PILE WORKER
MENTAL HEALTH HEARING OFFICER
ASSISTANT CHIEF VICTIM/WITNESS INVESTIGATOR
CHEMIST I/II
PARKING METER REPAIRER SUPERVISOR I
CONSERVATORSHIP/CASE MGNT SUPV
DEPUTY COURT CLERK III
AIRPORT COMMUNICATIONS SUPERVISOR
PRINCIPAL CLERK
PAINTER SUPERVISOR II
AREA SUPERVISOR, PARKS, SQUARES AND FACILITIES
FORESTER
PUBLIC RELATIONS OFFICER
EXECUTIVE SECRETARY III
CIVIL ENGINEERING ASSOCIATE I
AIRPORT EMERGENCY PLANNING COORDINATOR
MOBILE EQUIPMENT ASSISTANT SUPERVISOR
IS OPERATOR - SUPERVISOR
PERSONNEL ANALYST
CARPENTER SUPERVISOR II
EMPLOYMENT AND TRAINING SPECIALIST V
PARKING HEARING EXAMINER
GLAZIER SUPERVISOR I
SECRETARY, LIBRARY COMMISSION
EXECUTIVE SECRETARY TO THE CONTROLLER
ASSISTANT CONSTRUCTION INSPECTOR
SUPERVISING COURT ADMINISTRATIVE SECRETARY
SENIOR PARTS STOREKEEPER
ELIGIBILITY WORKER SUPERVISOR
MUSEUM GUARD
WELFARE FRAUD INVESTIGATOR
PRINCIPAL PARTS STOREKEEPER
SENIOR MANAGEMENT ASSISTANT
ASSOCIATE PERFORMANCE AUDITOR
MAINTENANCE ESTIMATOR AND SCHEDULER
PATIENT ACCOUNTS MANAGER
MARKET RESEARCH SPECIALISTS, PORT
SPECIAL ASSISTANT XV
SENIOR MARRIAGE, FAMILY & CHILD COUNSELOR (MFCC)
TRAINING OFFICER
NUTRITIONIST
LIBRARIAN II
SENIOR GENERAL UTILITY MECHANIC
WATER QUALITY TECHNICIAN I/II
X-RAY LABORATORY AIDE
EMERGENCY PROTECTIVE ORDERS COMMISSIONER
SENIOR MEDICAL SOCIAL WORKER
HEALTH EDUCATOR
IS ADMINISTRATOR I
CHIEF NURSERY SPECIALIST
POWERHOUSE ELECTRICIAN SUPERVISOR II
PROGRAM SPECIALIST SUPERVISOR
PORTER
IS ADMINISTRATOR II
SENIOR CENTRAL PROCESSING AND DISTRIBUTION TECHNIC
PAYROLL SUPERVISOR
TRIAL DELAY REDUCTION COORDINATOR
BUILDING SERVICES TECHNICIAN
SENIOR FISCAL TECHNICIAN
IS TECHNICIAN - SUPERVISOR
EMPLOYMENT & TRAINING SPECIALIST IV
PUBLIC HEALTH TEAM LEADER
PRINCIPAL INVESTIGATOR, TAX COLLECTOR
MICROBIOLOGIST
CENTRAL PROCESSING AND DISTRIBUTION TECHNICIAN
SIGN WORKER
MEDIA TRAINING SPECIALIST
MEDICAL RECORDS TECHNICIAN SUPERVISOR
CUSTODIAL ASSISTANT SUPERVISOR
SENIOR EMPLOYEE ASSISTANCE COUNSELOR
MEDIA PRODUCTION SUPERVISOR
COMMERCIAL DIVISION ASSISTANT SUPERVISOR
CHILD SUPPORT OFFICER III
CRIMINAL JUSTICE SPECIALIST II
DENTAL HYGIENIST
ROOFER SUPERVISOR I
JUNIOR ENGINEER
COURT AD RESOLUTION COORDINATOR
PATIENT ACCOUNTS ASSISTANT SUPERVISOR
TRAINING TECHNICIAN
TREE TOPPER SUPERVISOR II
VICTIM/WITNESS INVESTIGATOR III
PHYSICAL THERAPIST ASSISTANT
ORNAMENTAL IRON WORKER
HEALTH PROGRAM COORDINATOR II
INVESTIGATOR, OFFICE OF CITIZEN COMPLAINTS
ARCHITECTURAL ASSISTANT II
HEALTH PROGRAM PLANNER
CONFIDENTIAL SECRETARY TO DISTRICT ATTORNEY
ASSOCIATE HUMAN RESOURCES ANALYST
ASSISTANT DIRECTOR, LOG CABIN RANCH
MEDICAL RECORDS TECHNICIAN
MEDICAL SOCIAL WORKER
SENIOR ESTATE INVESTIGATOR
SECURITY GUARD
PUBLIC DEFENDER'S INVESTIGATOR
INVESTIGATOR, TAXI & ACCESS SVCS
SENIOR FARE COLLECTIONS RECEIVER
CHIEF DIETITIAN
SURVEY ASSISTANT II
PUBLIC SERVICE TRAINEE
LIBRARIAN II - ASIAN ARTS
DEPUTY COURT CLERK II
ASSISTANT STOREKEEPER
REAL PROPERTY APPRAISER
REPRESENTATIVE, HUMAN RIGHTS COMMISSION
COUNSELOR, JUVENILE HALL
TRANSIT PLANNER II
RETIREMENT ANALYST
PLANNER II
ASSISTANT INDUSTRIAL HYGIENIST
EMPLOYEE ASSISTANCE COUNSELOR
ADMINISTRATIVE ANALYST
SPECIALIST IN AGING II
REHABILITATION SERVICES COORDINATOR
AFFIRMATIVE ACTION SPECIALIST
POWER GENERATION TECHNICIAN I
TREE TOPPER
WATER QUALITY TECHNICIAN III
EMPLOYEE RELATIONS REPRESENTATIVE
STATION OFFICER
REPRESENTATIVE, COMMISSION ON THE STATUS OF WOMEN
METAL FABRICATOR
EXECUTIVE SECRETARY II
WATERSHED KEEPER SUPERVISOR
MAYORAL STAFF XII
MEDICAL STAFF SERVICES DEPARTMENT ANALYST
UNIT CLERK
ASSISTANT HEALTH EDUCATOR
UTILITY ANALYST
ENVIRONMENT SPECIALIST
LEGAL ASSISTANT
INVESTIGATOR, TAX COLLECTOR
SENIOR ELIGIBILITY WORKER
SOCIAL WORK SUPERVISOR
CONFIDENTIAL SECRETARY CITY ATTORNEY
IS TRAINER - JOURNEY
MEDICAL EVALUATIONS ASSISTANT
HEALTH CARE BILLING CLERK II
PERSONAL PROPERTY AUDITOR
NURSES STAFFING ASSISTANT
PURCHASER
PROGRAM SPECIALIST
COURT ASSISTANT, SUPERIOR COURT
EMERGENCY PLANNING COORDINATOR
PEST CONTROL SPECIALIST
ROOFER
DIRECTOR OF ACTIVITIES, THERAPY AND VOLUNTEER SERV

In [44]:
df.JobTitle.nunique()

2159

## ***10. Total Number of Job Titles Contain Captain***

In [53]:
df[df.JobTitle.str.contains('CAPTAIN')]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.0,87082.62,110804.3,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
8684,JEANNE SEYLER,"CAPTAIN, FIRE SUPPRESSION",95055.34,0.0,9197.14,NaN,104252.48,104252.48,2011
10485,JANE SMITH,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",74592.0,1538.59,18804.68,NaN,94935.27,94935.27,2011
11198,KATHRYN BROWN,CAPTAIN III (POLICE DEPARTMENT),10684.5,0.0,81244.87,NaN,91929.37,91929.37,2011
31297,MARCO CARNIGLIA,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",9839.72,0.0,1203.77,NaN,11043.49,11043.49,2011
34124,JOHN FORBES-3,"CAPTAIN, FIRE SUPPRESSION",0.0,982.06,2277.34,NaN,3259.40,3259.40,2011

In [55]:
df[df.JobTitle.str.contains('CAPTAIN',case=False)]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
11,PATRICIA JACKSON,CAPTAIN III (POLICE DEPARTMENT),99722.0,87082.62,110804.3,NaN,297608.92,297608.92,2011
17,SEBASTIAN WONG,"CAPTAIN, EMERGENCYCY MEDICAL SERVICES",140546.87,119397.26,18625.08,NaN,278569.21,278569.21,2011
22,GEORGE GARCIA,"CAPTAIN, FIRE SUPPRESSION",140546.88,93200.58,39955.25,NaN,273702.71,273702.71,2011
...,...,...,...,...,...,...,...,...,...
116604,Gregory L Stewart,"Captain, Fire Suppression",73355.21,18517.18,49917.73,25608.77,141790.12,167398.89,2014
120867,Michael J Moran,Captain 3,7660.0,1496.09,126560.36,2189.51,135716.45,137905.96,2014
122361,Michael V Rolovich,"Captain, Fire Suppression",0.0,0.0,130320.75,0.0,130320.75,130320.75,2014
126588,Stephen M Tittel,Captain 3,68491.89,0.0,23721.91,19020.79,92213.80,111234.59,2014
132232,Jeanne M Seyler,"Captain, Fire Suppression",61039.43,2285.30,7548.29,20113.76,70873.02,90986.78,2014

In [57]:
df[df.JobTitle.str.contains('CAPTAIN',case=False)].sum()

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [59]:
df.JobTitle.str.contains('CAPTAIN',case=False).sum()

552

## ***11. Display All The Employee Names From Fire Department***

In [61]:
df.JobTitle.str.contains('fire',case=False).sum()

5879

In [63]:
df[df.JobTitle.str.contains('fire',case=False)]

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011
6,ALSON LEE,"BATTALION CHIEF, (FIRE DEPARTMENT)",92492.01,89062.9,134426.14,NaN,315981.05,315981.05,2011
8,MICHAEL MORRIS,"BATTALION CHIEF, (FIRE DEPARTMENT)",176932.64,86362.68,40132.23,NaN,303427.55,303427.55,2011
9,JOANNE HAYES-WHITE,"CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",285262.0,0.0,17115.73,NaN,302377.73,302377.73,2011
10,ARTHUR KENNEY,"ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)",194999.39,71344.88,33149.9,NaN,299494.17,299494.17,2011
...,...,...,...,...,...,...,...,...,...
145956,Kenneth C Farris,Firefighter,0.00,0.00,0.00,4645.56,0.00,4645.56,2014
147556,Edward A Dunn,Firefighter,1063.24,0.00,132.90,385.66,1196.14,1581.80,2014
148021,Kari A Johnson,Firefighter,688.71,0.00,0.00,143.39,688.71,832.10,2014
148209,Sheryl K Lee,Firefighter,459.14,0.00,0.00,95.59,459.14,554.73,2014
148554,Lawrence F Gatt,Fire Alarm Dispatcher,73.33,0.00,0.00,0.73,73.33,74.06,2014

In [65]:
df[df.JobTitle.str.contains('fire',case=False)]['EmployeeName']

4            PATRICK GARDNER
6                  ALSON LEE
8             MICHAEL MORRIS
9         JOANNE HAYES-WHITE
10             ARTHUR KENNEY
                 ...
145956      Kenneth C Farris
147556         Edward A Dunn
148021        Kari A Johnson
148209          Sheryl K Lee
148554       Lawrence F Gatt
Name: EmployeeName, Length: 5879, dtype: object

## ***12. Find Minimum, Maximum, Average BasepPay***

In [71]:
df.BasePay.astype(float)

ValueError: could not convert string to float: 'Not Provided'

In [81]:
df.BasePay = df.BasePay.replace('Not Provided',0).astype(float)

In [83]:
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,Not provided,Not provided,0.00,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,Not provided,Not provided,0.00,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,Not provided,Not provided,0.00,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

In [85]:
df.BasePay.describe()

count    148049.000000
mean      66323.656854
std       42765.447379
min        -166.010000
25%       33583.520000
50%       65006.930000
75%       94691.050000
max      319275.010000
Name: BasePay, dtype: float64

In [87]:
df.BasePay.min()

-166.01

In [89]:
df.BasePay.max()

319275.01

## ***13. Replace 'Not Provided' in EmployeeName Column to NaN***

In [ ]:
np.nan

In [97]:
df.EmployeeName = df.EmployeeName.replace('Not provided',np.nan)

In [99]:
df.EmployeeName

0            NATHANIEL FORD
1              GARY JIMENEZ
2            ALBERT PARDINI
3         CHRISTOPHER CHONG
4           PATRICK GARDNER
                ...
148649        Roy I Tillery
148650                  NaN
148651                  NaN
148652                  NaN
148653            Joe Lopez
Name: EmployeeName, Length: 148654, dtype: object

## ***14. Find Job Title of ALBERT PARDINI***

In [109]:
df[df['EmployeeName'] == 'ALBERT PARDINI'].JobTitle

2    CAPTAIN III (POLICE DEPARTMENT)
Name: JobTitle, dtype: object

## ***15. How Much ALBERT PARDINI Make (Include TotalPayBenefits)?***

In [113]:
df[df['EmployeeName'] == 'ALBERT PARDINI'].TotalPayBenefits

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [111]:
df

,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year
0,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011
1,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011
2,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011
3,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.9,NaN,332343.61,332343.61,2011
4,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.0,182234.59,NaN,326373.19,326373.19,2011
...,...,...,...,...,...,...,...,...,...
148649,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014
148650,NaN,Not provided,0.00,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148651,NaN,Not provided,0.00,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148652,NaN,Not provided,0.00,Not Provided,Not Provided,Not Provided,0.00,0.00,2014
148653,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014

## ***16. Find Average BasePay Of All Employee Per Year***

In [117]:
df.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66557.437750
Name: BasePay, dtype: float64

## ***17. Find Average BasePay Of All Employee Per Job Title***

In [119]:
df.groupby('JobTitle')['BasePay'].mean()

JobTitle
ACCOUNT CLERK                                     43300.806506
ACCOUNTANT                                        46643.172000
ACCOUNTANT INTERN                                 28732.663958
ACPO,JuvP, Juv Prob (SFERS)                       62290.780000
ACUPUNCTURIST                                     66374.400000
                                                      ...
X-RAY LABORATORY AIDE                             47664.773077
X-Ray Laboratory Aide                             46086.387100
YOUTH COMMISSION ADVISOR, BOARD OF SUPERVISORS    52609.910000
Youth Comm Advisor                                39077.957500
ZOO CURATOR                                       43148.000000
Name: BasePay, Length: 2159, dtype: float64

## ***18. Find Average BasePay Of Employee Having Job Title ACCOUNTANT***

In [127]:
df[df['JobTitle'] == 'ACCOUNTANT']['BasePay'].mean()

46643.172

## ***19. Find Top 5 Most Common Jobs***

In [137]:
df['JobTitle'].value_counts().head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64